package:
  name: buffersort
  version: "0.0.5"
 
source:
  git_rev: v0.0.5
  git_url: https://github.com/spearsem/buffersort.git

# Template for hosting from pypi instead.
#fn: buffersort-0.0.5.tar.gz
#md5: # place hash checksum here.
#url: https://pypi.python.org/pypi/buffersort/0.0.5
 
requirements:
  build:
    - python
    - cython >=0.22
    - numpy >=1.10.1
  run:
    - python
    - numpy >=1.10.1
 
test:
  imports:
    - buffersort
  commands:
    - cd $HOME; python -c 'import buffersort;
          buffersort.test_buffersort.run_tests(alert=True)'
 
about:
  home: https://github.com/spearsem/buffersort
  license: GNU GPL
  license_file: LICENSE.txt